#!/usr/bin/env python3
import json
import re
from datetime import datetime, timezone

INPUT_FILE = "data.json"
OUTPUT_FILE = "feed_all.xml"
OUTPUT_FILE_NO_CLEAN = "feed_main.xml"
OUTPUT_FILE_CLEAN = "feed_clean.xml"


# -------------------------
# Date parsing
# -------------------------
def parse_any_date(s: str) -> datetime:
    s = s.strip()

    try:
        return datetime.strptime(s, "%a, %d %b %Y %H:%M:%S %z").astimezone(timezone.utc)
    except ValueError:
        pass

    try:
        dt = datetime.strptime(s, "%Y-%m-%d")
        return dt.replace(tzinfo=timezone.utc)
    except ValueError:
        pass

    m = re.match(r"([A-Za-z]+) (\d{1,2}), (\d{4})", s)
    if m:
        month, day, year = m.groups()
        dt = datetime.strptime(f"{month} {day} {year}", "%B %d %Y")
        return dt.replace(tzinfo=timezone.utc)

    raise ValueError(f"Unknown date format: {s}")


def format_rfc822(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S %z")


def format_duration(total_minutes: int) -> str:
    hours, minutes = divmod(total_minutes, 60)
    return f"{hours:02}:{minutes:02}:00"


# -------------------------
# Description builder
# -------------------------
def build_description(ep):
    lines = [
        f'<a href="{ep["episode_url"]}">{ep["episode_url"]}</a>',
        "",
        ep["synopsis"].strip(),
        ""
    ]

    for act in ep.get("acts", []):
        lines.append(act.get("number_text", ""))
        summary = act.get("summary", "").strip()

        if act.get("duration"):
            summary += f" ({act['duration']} minutes)"
        if act.get("contributors"):
            summary += " by " + ", ".join(act["contributors"])

        lines.append(summary)
        lines.append("")

    orig_dt = parse_any_date(ep["original_air_date"])
    lines.append(f"Originally Aired: {orig_dt.strftime('%Y-%m-%d')}")

    return "<br>\n".join(lines)


# -------------------------
# Item builder
# -------------------------
def make_item(ep, *, use_clean=False, force_include_clean=False):
    has_clean = bool(ep.get("download_clean"))

    # rules
    if use_clean and not has_clean:
        return None

    if use_clean:
        url = ep["download_clean"]
        suffix = " (Clean)"
        guid_suffix = "-C"
        explicit = "clean"
    else:
        url = ep["download"]
        suffix = ""
        guid_suffix = ""
        explicit = "true" if ep.get("explicit") else "false"

    title = f'{ep["number"]}: {ep["title"]}{suffix}'
    padded = ep["number"].zfill(4)

    latest_pub_dt = max(
        (parse_any_date(d) for d in ep.get("published_dates", [])),
        default=parse_any_date(ep["original_air_date"])
    )

    orig_dt = parse_any_date(ep["original_air_date"])
    title_suffix = " - Repeat" if latest_pub_dt.year != orig_dt.year else ""

    description = build_description(ep)
    total_minutes = sum((a.get("duration") or 0) for a in ep.get("acts", []))

    item = f"""    <item>
      <title><![CDATA[{title}{title_suffix}]]></title>
      <link>{ep["episode_url"]}</link>
      <guid>{padded}-{latest_pub_dt.strftime('%Y%m%d')}{guid_suffix}</guid>
      <itunes:season>{orig_dt.year}</itunes:season>
      <itunes:episode>{ep["number"]}</itunes:episode>
      <itunes:episodeType>full</itunes:episodeType>
      <itunes:explicit>{explicit}</itunes:explicit>
      <description><![CDATA[{description}]]></description>
      <pubDate>{format_rfc822(latest_pub_dt)}</pubDate>
      <enclosure url="{url}" type="audio/mpeg"/>
      <itunes:duration>{format_duration(total_minutes)}</itunes:duration>
    </item>"""

    return item


# -------------------------
# Feed writer
# -------------------------
def write_feed(path, items):
    header = """<?xml version="1.0" ?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">
  <channel>
    <title>That American Archive</title>
    <link>https://www.thisamericanlife.org</link>
    <description>Autogenerated feed</description>
    <language>en</language>
    <itunes:image href="https://i.imgur.com/pTMCfn9.png"/>"""

    footer = "  </channel>\n</rss>"

    with open(path, "w", encoding="utf-8") as f:
        f.write(header + "\n")
        f.write("\n".join(items) + "\n")
        f.write(footer + "\n")


# -------------------------
# Main
# -------------------------
def main():
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        episodes = json.load(f)

    all_items = []
    main_items = []
    clean_items = []

    for ep in episodes:
        if not ep.get("download"):
            continue

        normal = make_item(ep, use_clean=False)
        clean = make_item(ep, use_clean=True)

        # FULL FEED
        all_items.append(normal)
        if clean:
            all_items.append(clean)

        # MAIN FEED (NO CLEAN)
        main_items.append(normal)

        # CLEAN FEED (prefer clean, fallback normal)
        clean_items.append(clean if clean else normal)

    # write outputs
    write_feed(OUTPUT_FILE, all_items)
    write_feed(OUTPUT_FILE_NO_CLEAN, main_items)
    write_feed(OUTPUT_FILE_CLEAN, clean_items)


if __name__ == "__main__":
    main()
