#!/usr/bin/env python3
import json
from datetime import datetime, timezone

INPUT_FILE = "data.json"
OUTPUT_FILE = "feed.xml"

def format_rfc822(dt: datetime):
    dt_utc = dt.astimezone(timezone.utc)
    return dt_utc.strftime("%a, %d %b %Y %H:%M:%S %z")

def format_duration(total_minutes: int):
    hours, minutes = divmod(total_minutes, 60)
    return f"{hours:02}:{minutes:02}:00"

def build_description(ep):
    lines = [ep["synopsis"].strip(), ""]
    for act in ep.get("acts", []):
        lines.append(act["number_text"] if act["number_text"] != "Prologue" else "Prologue")
        summary_line = act["summary"].strip()
        if act.get("duration"):
            summary_line += f" ({act['duration']} minutes)"
        if act.get("contributors"):
            summary_line += " _" + ", ".join(act["contributors"]) + "_"
        lines.append(summary_line)
        lines.append("")
    lines.append(f"Originally Aired: {datetime.strptime(ep['original_air_date'], '%a, %d %b %Y %H:%M:%S %z').strftime('%Y-%m-%d')}")
    return "\n".join(lines)

def main():
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        episodes = json.load(f)

    episodes = sorted(episodes, key=lambda x: int(x["number"]))

    items = []
    for ep in episodes:
        for pub_date_str in ep.get("published_dates", []):
            if not ep.get("download"):
                continue

            pub_dt = datetime.strptime(pub_date_str, "%a, %d %b %Y %H:%M:%S %z")
            orig_dt = datetime.strptime(ep["original_air_date"], "%a, %d %b %Y %H:%M:%S %z")
            is_repeat = pub_dt.year != orig_dt.year
            title_suffix = " - Repeat" if is_repeat else ""
            rss_title = f'{ep["number"]}: {ep["title"]}{title_suffix}'

            total_minutes = sum((act.get("duration") or 0) for act in ep.get("acts", []))
            description = build_description(ep)

            guid_base = f'{ep["number"]}-{pub_dt.strftime("%Y%m%d")}'

            # Main episode
            item_lines = [
                "    <item>",
                f"      <title>{rss_title}</title>",
                f"      <link>{ep['episode_url']}</link>",
                f"      <guid>{guid_base}</guid>",
                f"      <itunes:episode>{ep['number']}</itunes:episode>",
                "      <itunes:episodeType>full</itunes:episodeType>",
                f"      <itunes:explicit>{'true' if ep['explicit'] else 'clean'}</itunes:explicit>",
                f"      <description>{description}</description>",
                f"      <pubDate>{format_rfc822(pub_dt)}</pubDate>",
                f"      <enclosure url=\"{ep['download']}\" type=\"audio/mpeg\"/>",
                f"      <itunes:duration>{format_duration(total_minutes)}</itunes:duration>",
            ]
            if ep.get("image") and ep["image"].get("url"):
                item_lines.append(f"      <itunes:image href=\"{ep['image']['url']}\"/>")
            item_lines.append("    </item>")
            items.append("\n".join(item_lines))

            # Clean version
            if ep.get("download_clean"):
                rss_title_clean = f'{ep["number"]}: {ep["title"]}{title_suffix} (Clean)'
                guid_clean = f"{guid_base}-C"
                item_lines_clean = [
                    "    <item>",
                    f"      <title>{rss_title_clean}</title>",
                    f"      <link>{ep['episode_url']}</link>",
                    f"      <guid>{guid_clean}</guid>",
                    f"      <itunes:episode>{ep['number']}</itunes:episode>",
                    "      <itunes:episodeType>full</itunes:episodeType>",
                    "      <itunes:explicit>clean</itunes:explicit>",
                    f"      <description>{description}</description>",
                    f"      <pubDate>{format_rfc822(pub_dt)}</pubDate>",
                    f"      <enclosure url=\"{ep['download_clean']}\" type=\"audio/mpeg\"/>",
                    f"      <itunes:duration>{format_duration(total_minutes)}</itunes:duration>",
                ]
                if ep.get("image") and ep["image"].get("url"):
                    item_lines_clean.append(f"      <itunes:image href=\"{ep['image']['url']}\"/>")
                item_lines_clean.append("    </item>")
                items.append("\n".join(item_lines_clean))

    rss_header = """<?xml version="1.0" ?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">
  <channel>
    <title>This American Archive</title>
    <link>https://www.thisamericanlife.org</link>
    <description>Autogenerated feed of the This American Life archive with explicit and clean episodes.</description>
    <language>en</language>
    <copyright>Copyright © Ira Glass / This American Life</copyright>
    <itunes:image href="https://i.imgur.com/pTMCfn9.png"/>"""

    rss_footer = "  </channel>\n</rss>"

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(rss_header + "\n")
        f.write("\n".join(items) + "\n")
        f.write(rss_footer + "\n")

if __name__ == "__main__":
    main()
