#!/usr/bin/env python3
import json
from datetime import datetime, timezone, timedelta

INPUT_FILE = "data.json"
OUTPUT_FILE = "feed.xml"

def format_rfc822(dt: datetime):
    dt_utc = dt.astimezone(timezone.utc)
    return dt_utc.strftime("%a, %d %b %Y %H:%M:%S %z")

def format_duration(total_minutes: int):
    hours, minutes = divmod(total_minutes, 60)
    return f"{hours:02}:{minutes:02}:00"

def parse_date(date_str):
    try:
        return datetime.strptime(date_str, "%Y-%m-%d")
    except ValueError:
        return datetime.strptime(date_str[:25], "%a, %d %b %Y %H:%M:%S")

def build_description(ep):
    lines = [ep["episode_url"], "", ep["synopsis"].strip(), ""]

    for act in ep.get("acts", []):
        lines.append(act["number_text"] if act["number_text"] != "Prologue" else "Prologue")
        summary_line = act["summary"].strip()
        if act.get("duration"):
            summary_line += f" ({act['duration']} minutes)"
        if act.get("contributors"):
            summary_line += " by " + ", ".join(act["contributors"])
        lines.append(summary_line)
        lines.append("")  # extra newline between acts

    lines.append(f"Originally Aired: {datetime.strptime(ep['original_air_date'], '%a, %d %b %Y %H:%M:%S %z').strftime('%Y-%m-%d')}")
    return "\n".join(lines)

def generate_item(ep, is_clean=False):
    latest_pub_dt = max((parse_date(d) for d in ep.get("published_dates", [])))
    orig_dt = datetime.strptime(ep["original_air_date"], "%a, %d %b %Y %H:%M:%S %z")
    is_repeat = latest_pub_dt.year != orig_dt.year
    title_suffix = " - Repeat" if is_repeat else ""
    if is_clean:
        title_suffix += " (Clean)"
    description = build_description(ep)
    total_minutes = sum((act.get("duration") or 0) for act in ep.get("acts", []))
    padded_number = ep["number"].zfill(4)
    guid = f"{padded_number}-{latest_pub_dt.strftime('%Y%m%d')}{'-C' if is_clean else ''}"
    explicit_val = "clean" if is_clean else ("yes" if ep.get("download_clean") else "no")
    download_url = ep["download_clean"] if is_clean else ep["download"]

    item = f"""    <item>
      <title>{ep["number"]}: {ep["title"]}{title_suffix}</title>
      <link>{ep["episode_url"]}</link>
      <guid>{guid}</guid>
      <itunes:season>{orig_dt.year}</itunes:season>
      <itunes:episode>{ep["number"]}</itunes:episode>
      <itunes:episodeType>full</itunes:episodeType>
      <itunes:explicit>{explicit_val}</itunes:explicit>
      <description><![CDATA[{description}]]></description>
      <pubDate>{format_rfc822(latest_pub_dt)}</pubDate>
      <enclosure url="{download_url}" type="audio/mpeg"/>
      <itunes:duration>{format_duration(total_minutes)}</itunes:duration>"""
    if ep.get("image") and ep["image"].get("url"):
        item += f'\n      <itunes:image href="{ep["image"]["url"]}"/>'
    item += "\n    </item>"
    return item

def main():
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        episodes = json.load(f)

    items = []
    for ep in episodes:
        if not ep.get("download"):
            continue
        items.append(generate_item(ep, is_clean=False))
        if ep.get("download_clean"):
            items.append(generate_item(ep, is_clean=True))

    # Sort descending by pubDate
    items.sort(key=lambda x: parse_date(x.split("<pubDate>")[1].split("</pubDate>")[0]), reverse=True)

    rss_header = """<?xml version="1.0" ?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">
  <channel>
    <title>That American Archive</title>
    <link>https://www.thisamericanlife.org</link>
    <description>Autogenerated feed of the This American Life archive with explicit and clean episodes.</description>
    <language>en</language>
    <copyright>Copyright © Ira Glass / This American Life</copyright>
    <itunes:image href="https://i.imgur.com/pTMCfn9.png"/>"""

    rss_footer = "  </channel>\n</rss>"

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(rss_header + "\n")
        f.write("\n".join(items) + "\n")
        f.write(rss_footer + "\n")

if __name__ == "__main__":
    main()
